EXCLUDED = ['ClassProbabilities',
            'CardinalitiesOfCategoricalFeatures',
            'CardinalitiesOfNumericFeatures',
            'MeansOfNumericFeatures',
            'StdDevsOfNumericFeatures',
            'SkewnessesOfNumericFeatures',
            'KurtosesOfNumericFeatures',
            'CategoricalAttributeEntropies',
            'NumericAttributeEntropies',
            'CategoricalJointEntropies',
            'NumericJointEntropies',
            'CategoricalMutualInformation',
            'NumericMutualInformation',
            'MeansOfStringLengthOfTextFeatures',
            'StdDevsOfStringLengthOfTextFeatures',
            'SkewnessesOfStringLengthOfTextFeatures',
            'KurtosesOfStringLengthOfTextFeatures']
